---
title: "Conectando o RStudio ao GitHub usando R"
format: gfm
editor: visual
---

> Guia prático e simples para usuários de R que não são da área de tecnologia, usando apenas 3 pacotes

O GitHub é uma platafornma muito últil a diversos tipos de programadores, para o armazenamento e versionamento dos seus códigos. Para profissionais que usam a programação fortemente nas suas vidas mas não são da área de tecnologia, como biólogos (o meu caso), alguns conceitos e operações sobre Git e GitHub podem ser pouco intuitívas. Mais ainda, operações sobre como conectar IDEs de programação, como o RStudio, ao GitHub, podem se tornar desafios ainda maiores.

Desta foram, o objetivo deste guia é apresentar uma forma prática de não apenas entender como o GitHub funciona, mas como trabalhar com ele, usando apenas linguagem de programação R, pensando em usuários de programação que não são da área de tecnologia.

# Introdução **BEM** geral: Git, GitHub e o fluxo de trabalho de versionamento

::: callout-important
Imagino que você deva estar com muita pressa para pôr a mão-na-massa, mas antes de ir para os códigos, leia esta introdução **BEM** geral. Ela te explicará alguns conceitos chaves que, sem ele, você não entenderá o código.
:::

```{mermaid} 
flowchart LR
  A{**Projeto**} --> B[**Branch main**] 
  A --> C[**Branch paralela**]
  B --> D[**Adicionar o arquivo**]
  D --> E[**Commitando a mudança**]
  E --> F[**Pushando para o respositório**]
  F --> G[**Pullando do respositório**]
  H[**Removendo arquivo**] --> E
  D --> I[**Resetar arquivos adicionados**]
  E --> J[**Resetar commits**]
  B --> H
  B --> K[**Mergendo as branches**]
  C --> K[**Mergendo as branches**]
  B --> L[**Status dos arquivos que possuem mudanças**]
  style A fill:forestgreen, color:black, stroke:black, stroke-width:2px
  style B fill:gold, color:black, stroke:black, stroke-width:2px
  style C fill:royalblue, color:black, stroke:black, stroke-width:2px
  style D fill:goldenrod, color:black, stroke:black, stroke-width:2px
  style E fill:goldenrod, color:black, stroke:black, stroke-width:2px
  style F fill:goldenrod, color:black, stroke:black, stroke-width:2px
  style G fill:goldenrod, color:black, stroke:black, stroke-width:2px
  style H fill:orangered, color:black, stroke:black, stroke-width:2px
  style I fill:tomato, color:black, stroke:black, stroke-width:2px
  style J fill:tomato, color:black, stroke:black, stroke-width:2px
  style K fill:lightgreen, color:black, stroke:black, stroke-width:2px
  style L fill:yellow, color:black, stroke:black, stroke-width:2px
  linkStyle default stroke-width:3px
```

# Pacotes necessários

::: callout-important
Antes de carregar os pacotes, certifique os mesmos estão previamente instalados. Caso não, instale-os usando a função `install.packages()`.
:::

```{r}
#| eval: false
#| 
library(usethis)

library(gitcreds)

library(gert)
```


